### ISSUE TITLE
Functions defined in list patterns cause exceptions

### ISSUE THREAD

**Issue by gensofubi** [hazelgrove/hazel#1044]
The input 
`let [a] = [fun x -> x+1] in a(1)`
will cause (Exception "Haz3lcore.EvaluatorError.Exception(_)")

On the other hand, it works well if we type-annotate either the list or `a` itself. But bad syntax in the annotation will cause the same exception.

**Comment by gensofubi** [comment]
Similar problem appears in module system (which I'm working on). Thoughts on the possible cause would be appreciated.

**Comment by disconcision** [comment]
Commenting to remind myself that I noticed a weird edge case involving list literal patterns in the fantasyland hazel branch that may be related... I'll try to dig it up.

**Comment by disconcision** [comment]
@cyrus- : this happens because the fn literal ends up in analytic against unknown internal (instead of unknown synswitch). this happens because the type of the pattern (when synthesizing the pattern type with synswitch=true) is list(unknown(internal)). this happens because the self type of a listlit pattern is given by the join of its element types. here the element's type is synswitch, but the multivariate join, join_all, is currently defined as a fold over join with base element unknown(internal), which predominates over unknown(synswitch).

On reflection the join_all base case is ill-specified, so I'm folding a fix to this into ADTs, changing join_all to require that the fold base be specified, and providing either unknown internal or synswitch as appropriate in the pattern case, but I'm posting here just in case I'm missing something with this solution.
