### ISSUE TITLE
cannot apply a function to unit input

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1048]
![image](https://github.com/hazelgrove/hazel/assets/280638/40e42e2c-33f6-4ed1-96bf-4de2b0950460)

creates a grout in between

**Comment by disconcision** [comment]
disagree that this is a bug instead of an enhancement. you can apply a function to unit input, in a syntactically consistent way, i.e. `f(())`.

that said i'm in favor of this change, but it's worth thinking a bit about at what level of abstraction to accomplish it. given that we've definitively decided to forgo currying, we could decide to accomplish this without special-casing by returning to space ap, which would become a strict generalization of the current tight-ap arrangement

**Comment by gensofubi** [comment]
This automatic inserted hole also includes a bug associated with the editor? which is troublesome when I want to modify the arguments of a function. After I delete the original argument within the parentheses, my cursor appears after the newly generated hole. When I move the cursor backward, it is visually moving, but its actual position remains the same place after that hole and I am unable to insert a new argument inside the parentheses, until I move the cursor to somewhere before the hole.

**Comment by cyrus-** [comment]
cannot apply a function with no arguments if you will instead

I don't think it's a problem to special case this in the same way that unit and nil are special cased...
