### ISSUE TITLE
sum type constructor functions should use the type alias instead of its normalized form

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1098]
e.g. the type of Nil and Cons shouldn't have rec in them

**Comment by disconcision** [comment]
@cyrus- the current behavior is due to the following:

Given the type definition:
`type T = A(Int) + B(T) in ...`

the type `T` has internal representation:
`(Sum
   [("A", (Some Int));
     ("B",
      (Some (Rec ("α",
               (Sum [("A", (Some Int)); ("B", (Some (Var "α")))])))))])`

and when we gather the constructor types, we unroll the type to stop the α from escaping, as commented here:
https://github.com/hazelgrove/hazel/blob/e908f4772669c84e43f3249b568177c3f81d4541/src/haz3lcore/statics/TypBase.re#L397. 

I don't remember the specific issue which inspired this addition; it may no longer be an issue since we have prohibited shadowing aliases. Since this is the case, perhaps we can just renaming the internal rec parameter to the type alias and forgo in the unrolling, though this seems like a hazard that would need to be warded in case we decided to change course on type shadowing.
