### ISSUE TITLE
Fixpoint evaluation rules have bad edge cases

### ISSUE THREAD

**Issue by Negabinary** [hazelgrove/hazel#1198]
I'm pretty sure this should evaluate to 3 not 13.

![image](https://github.com/hazelgrove/hazel/assets/31668468/0793ddfa-76c4-49c8-9a50-7494b9c07a74)

I think this can be fixed by re-implementing the rules in https://github.com/hazelgrove/phi/blob/15-environment-based-evaluation/15-environment-based-evaluation/assets/eval-environment-report.pdf

**Comment by cyrus-** [comment]
This is a pretty critical bug! Can you take a look and come up with a fix, @Negabinary?

**Comment by mirryi** [comment]
I recall having extensive discussions about issues in relation to evaluating fixpoints with @cyrus- on Slack maybe a year and a half ago... but I don't really recall what the issue was or what we ended up doing about it. However, in particular I'm fairly certain the rules in the thesis for fixpoint evaluation are wrong

**Comment by Negabinary** [comment]
ah thanks for the warning @mirryi ! I'll tread carefully.
