### ISSUE TITLE
prevent unnecessary fixpoints in elaboration

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#1268]
It appears that even non-recursive functions now have fixpoints around them:
![image](https://github.com/hazelgrove/hazel/assets/280638/a657b0ad-1c65-427f-af04-97a1420531c7)

@pigumar1 maybe you can take a look at this since you were working on related code recently? not sure if it is directly connected to your PR

**Comment by pigumar1** [comment]
@cyrus- I think this was introduced by my PR, since we made a decision that we should make functions always recursive, so we always elaborate a user function to a fixpoint. This decision was made before we have this (small-step evaluator?) feature.
![image](https://github.com/hazelgrove/hazel/assets/108375845/6c390324-34db-4f81-bd0e-5582db6c71ab)

One way I come up with that can (possibly) address this is to check if the function name appears in the function body as a free variable. If not, we don't elaborate a fixpoint.

**Comment by cyrus-** [comment]
While we should include the self-reference in the context from the perspective of type-checking, during elaboration I do think it would be worthwhile to check if it is used (this should already be tracked in the co-context) and if not, we don't include the fixpoint...
