### ISSUE TITLE
swap actions not working

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#248]
tried on my laptop and desktop, both running Linux -- something about keyboard handling? I think we might need to consider an alternative key binding if it works on some machines but not others.

**Comment by Yuning30** [comment]
Hi, I've tested with Chrome on Ubuntu 18.04 64bit. And the swap actions failed because the shortcuts we assigned for the swap actions are also used by the Ubuntu system for switching between different workspaces.

**Comment by Yuning30** [comment]
On Ubuntu, if we execute command
 `gsettings list-recursively | grep org.gnome.desktop.wm.keybindings | sort` 
in a terminal and scan for the key bindings for `<Ctrl><Alt>Up`, etc. The result is in the following picture.
![keybinding](https://user-images.githubusercontent.com/46411193/81734315-5068b780-9461-11ea-9b3f-ffebe44db41c.png)

Should we change to different key bindings?

**Comment by cyrus-** [comment]
Yes I think we should use different keybindings. How about Ctrl+Alt+I/J/K/L?

**Comment by Yuning30** [comment]
The new pull request changes the bindings of swap actions and I tested and worked on both Windows and Ubuntu. 

**However, the key binding issue is not the only problem that makes the swap actions fail to work.**  
If we use the code of the `dev` branch, the swap actions will fail on both Windows and Linux system. The reason is that on line 78, we use `MoveKey.of_key(JSUtil.get_key(evt))` to identify if a key combination is movement or not. **This will make any combination involving the arrow keys being identified as a basic movement thus making the swap actions fail and perhaps future actions involving arrow keys.**

 https://github.com/hazelgrove/hazel/blob/9c49c5ca944db591c0b1d47c0ee5ad4467eaaabd/src/hazelweb/gui/Cell.re#L77-L81
