### ISSUE TITLE
Cannot insert `let` at start of `let` sequences, which only grow from start to end

### ISSUE THREAD

**Issue by matthewhammer** [hazelgrove/hazel#30]
The current action semantics for `let` construction assumes that the cursor gives the RHS of the constructed `let` form.  Sometimes, however, we want the cursor to give the BODY of the constructed `let` form, leaving the cursor in an empty RHS.

In particular, when we have an existing sequence of `let`s, there is currently no way to insert a new `let` at the start of the sequence.  Consequently, `let` sequences can only be constructed (currently) from the outside in (from the start of the sequence to the end, and never in any other order).

For example, you cannot currently insert a new `let` just ahead of the first `x`, below:
![image](https://user-images.githubusercontent.com/1183963/34256893-b0268510-e614-11e7-831f-dc482e242d33.png)

**Comment by cyrus-** [comment]
Yeah we definitely need multiple construction actions for these kinds of
terms that put the term under the cursor in different positions. I'll think
about this once we have infix ops and editing variables+numbers working,
since that will lay the groundwork for the next version of the action
language.

**Comment by dmoon1221** [comment]
Resolved via https://github.com/hazelgrove/hazel/pull/53
