### ISSUE TITLE
pattern scopes across tuples

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#440]
Wanted to confirm this is unintended behavior (a is in scope on b and vice-versa). This is on dev, not my pattern annotations branch. b being in scope on a seems debatably justified; the opposite slightly less so.

<img width="635" alt="Screen Shot 2020-10-20 at 6 22 50 PM" src="https://user-images.githubusercontent.com/22436459/96650780-71cbaa80-1301-11eb-904c-b78bb3d57e6b.png">
<img width="635" alt="Screen Shot 2020-10-20 at 6 22 44 PM" src="https://user-images.githubusercontent.com/22436459/96650781-71cbaa80-1301-11eb-8f0d-44671719edb5.png">

This behavior also feels a bit odd:

<img width="644" alt="Screen Shot 2020-10-20 at 6 34 48 PM" src="https://user-images.githubusercontent.com/22436459/96651607-274b2d80-1303-11eb-993c-80f67d5458b6.png">

In the absence of a non-linear pattern error, my assumption would be that this would result in shadowing, not the first capture predominating.

**Comment by cyrus-** [comment]
The context showing all of the other variables in the pattern sort of makes sense in that those are the variables you can't use at that position. However, it would be fine if it had none of the other variables in scope too.

On the a, a pattern, once we add duplicate variable warnings I think the first variable might as well "win", so that behavior might be okay.

**Comment by disconcision** [comment]
makes sense!
