### ISSUE TITLE
Cannot create Sum type in Let Line type annotation

### ISSUE THREAD

**Issue by nj-wilson** [hazelgrove/hazel#449]
![image](https://user-images.githubusercontent.com/1814193/99349135-37561e80-2869-11eb-87ac-32894c2ec8d1.png)
At this point, unable to create a Sum type by hitting `|`, simply a `FailedAction`.

Expected behavior is to be able to create a sum type annotation
![image](https://user-images.githubusercontent.com/1814193/99349285-99af1f00-2869-11eb-82f4-dc95a1decae4.png)

For what it's worth, it _can_ be created, should the right hand side already have an injection. Hitting `:` to create an annotation will correctly make a sum annotation.

**Comment by cyrus-** [comment]
@dedbox @Yuning30 let's keep binary sums around in some form even after we add full datatypes -- they will be useful for teaching. can you fix this in the course of the datatypes project?

I suspect this bug is just because the | operator for booleans was added at some point. The UHCode file has a way to have the emitted action depend on the cursor info, so should be an easy fix if so.

**Comment by cyrus-** [comment]
@disconcision if you're using sums for livelit definitions you might need to fix this bug too
