### ISSUE TITLE
slowdown with 12+ letlines

### ISSUE THREAD

**Issue by disconcision** [hazelgrove/hazel#536]
I was originally thinking this was a prettyprinting thing but it might not be.

the below program takes 3 second to register a keypress. it feels exponential in # of lines
![2021-08-16 19_00_53-Hazel](https://user-images.githubusercontent.com/22436459/129639785-e80df0a0-293e-490f-9786-92502005f08a.png)

it seems however that the only lines that 'count' are letlines that provide a pattern but no binding expression.

to illustrate, the following programs exhibit no slowdown:
![2021-08-16 19_01_50-Hazel](https://user-images.githubusercontent.com/22436459/129639924-b50b7ccb-83b9-4d4f-aba7-ceb4e685363d.png)
![2021-08-16 19_02_21-Hazel](https://user-images.githubusercontent.com/22436459/129639927-6bc3b1d9-c3b9-4cee-adce-c0be8f910d0a.png)

however the following program is slowing down as i remove the binding expressions:
![2021-08-16 19_03_09-Hazel](https://user-images.githubusercontent.com/22436459/129639981-13e32d0a-84d0-41ec-9e4b-72a32c419a9a.png)

These are the metrics:

== Hazel.create times ==
hazel.js:1641 Program.get_doc:                   0ms
hazel.js:1641 LayoutOfDoc.layout_of_doc:         0ms
hazel.js:1641 Program.get_doc:                   0ms
hazel.js:1641 LayoutOfDoc.layout_of_doc:         0ms
hazel.js:1641 UHCode.view:                       5ms
hazel.js:1641 Cell.view:                         5ms
hazel.js:1641 Page.view:                      16835ms
hazel.js:1641 Hazel.create:                   16835ms
hazel.js:1641 
== Update.apply_action times ==
hazel.js:1641 Program.get_doc:                   1ms
hazel.js:1641 LayoutOfDoc.layout_of_doc:         0ms
hazel.js:1641 Update.apply_action:

**Comment by cyrus-** [comment]
Ah, this is likely due to closures piling up exponentially -- each empty hole has all of the preceding variables in its closure, which themselves have all of their preceding variables, etc.

**Comment by cyrus-** [comment]
Should work faster if you turn off evaluation but that sidebar option seems buggy -- I get an "Invalid_argument "option is None"" exception when I try to insert let bindings when Evaluate is unchecked. :\

**Comment by cyrus-** [comment]
Ultimately the solution here is to move to an evaluator that uses environments rather than substitution, and also to put evaluation in a separate worker thread so it isn't limiting UI performance. For now, avoid having a large number of holes sequenced in the binding structure like that.

**Comment by jlam55555** [comment]
~Early POC of evaluation with environments: https://hazel.org/build/eval-environment/~

~Allows me to get all the way to the bottom of the alphabet without a slowdown.~ (Edit: see next post)

**Comment by jlam55555** [comment]
Update: I lied, my implementation wasn't complete. I didn't correctly implement the evaluation with holes, so the environment wasn't being saved in a hole. (The way you can see this is that the bound variable values don't show up in the right sidebar.) This is an easy fix: more or less save the current environment when a hole is reached. But when I implemented this the performance issue reappeared.

I spent yesterday investigating and I think the issue comes down to an expensive renumbering operation (via some basic benchmarking). The evaluate function (everything that's being done with substitution/environments) is fast, but the renumbering operation is double counting some hole instances. Take, for example:

```ocaml
let a = (* hole 1 *) in
(* hole 2 *) + (* hole 3 *)
```

If you inspect the context for hole 2, you get 1:1. If you inspect the context for hole 3, you get 1:2. I believe that these should be the same hole instance -- a new hole instance should only be created if a hole actually is instantiated multiple times, such as in a function body. But in this case there is truly one instantiation of the hole.

This causes the hole instances numbers to blow up in the example that sparked this thread, and the renumbering step creates a lot of duplicate instances. I'm assuming this is what was meant by "environments versus substitution" that @cyrus- originally mentioned: we need to identify holes by the ones that come from the same evaluation environment to prevent this blowup. (I didn't understand this comment about environments thoroughly when I first read it.)

I don't think that [this](https://github.com/hazelgrove/hazel/issues/536#issuecomment-899889167) is the cause of the problem, since structural sharing should make the creation of new closure relatively efficient. (I also looked into this yesterday, and I think  `Evaluator.extend` can be optimized to use structural sharing a bit more. But this doesn't seem to be the root cause of the performance problem.)

The other thing that could be improved for performance is the fact that `Program.get_result` (which actually evaluates the program) is being evaluated way too often -- for every action (even for move actions, which shouldn't cause any change in the program result) the program is being run four times: twice in `Model.update_program`, and twice in `ContextInspector`. I don't understand `incr_dom` too well, but I believe that we can store the last evaluated program result in the `Model` and be able to use that for all of these instances. This alone would give a 4x speedup. Also, if we prevent evaluation on all but edit actions (such as on toggling sidebars and move actions) this should greatly improve performance in general.

@cyrus- Can you take a look at this and make sure this is correct? Also, is the hole renumbering step documented well somewhere?

**Comment by disconcision** [comment]
just a note: the evaluator call in get_result is memoized so repeated calls probably don't result in a significant slowdown

**Comment by jlam55555** [comment]
@disconcision Good to know. I just checked to see if the first calls to evaluate upon any changes were slower, but evaluate is consistently very fast. On my system (with the fabulous single-core performance of an Ivy bridge CPU) each call to `evaluate` (including the first one) takes <0.001s, while each call to `renumber` takes ~0.5s by the time I reach "m" (13 `let` statements).

Removing the memoization from `Evaluator.evaluate` has no effect here. Interestingly, trying to memoize `renumber` in the same way doesn't seem to speed up repeated calls at all.
