### ISSUE TITLE
cursor placement on comma insertion when analyzing against product type is incorrect

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#583]
pressing comma here leaves the cursor before the 5 rather than after the comma as expected. this may be a regression from #574 that slipped in, or never fixed in that PR. correct behavior is to the first hole in the completed tuple, rather than to the first position in the tuple

![Screenshot from 2022-02-28 00-56-44](https://user-images.githubusercontent.com/280638/155931803-5ff13567-1585-4b47-83a7-8babae126ef6.png)

**Comment by AlienKevin** [comment]
> pressing comma here leaves the cursor before the 5 rather than after the comma as expected. this may be a regression from #574 that slipped in, or never fixed in that PR. **correct behavior is to the first hole in the completed tuple**, rather than to the first position in the tuple
> 
> ![Screenshot from 2022-02-28 00-56-44](https://user-images.githubusercontent.com/280638/155931803-5ff13567-1585-4b47-83a7-8babae126ef6.png)

I can think of 3 possible understanding of the correct behavior and not sure which one is the expected behavior:
1. first empty hole after the cursor
2. first empty hole in the tuple
3. first empty/filled hole in the tuple

Personally, I think option 1 makes the most sense because by pressing comma, the user usually intends to fill out the new empty hole after the cursor, not going back to the first empty/filled hole when there's one. This is also consistent with cases with mismatched tuple length. For example: `let x : (Int, Int, Int) = _, 5| in ...` Pressing "," after 5 inserts an empty hole and I think the user expects the cursor to be placed at the new hole rather than going all the way back to the first hole before 5.
Option 3 is particularly tricky to implement, because a hole before tuple completion can either remain as a hole or become a valid element of the tuple. However, at the time of completion, we don't know which option it will take without comparing the type of the hole with the type declaration.
Example of filled hole: `let x : (Int, Int) = t| in ...` Since t is undefined, if I press "," hazel will autocomplete a comma and insert a new hole after t. Should I place the cursor at the filled hole containing t or at the new empty hole after t?

**Comment by cyrus-** [comment]
I think we should place the cursor at the next position after the comma when tuple completion is triggered by a comma, regardless of where any holes may be inserted. Otherwise you'll have situations like `5| 6` when analyzed against a 3-tuple where the first hole skips past the 6.

If tuple completion is triggered by open parentheses, then I think it makes sense to place the cursor at the first hole in the tuple, which will always either be in the first position if there was already a hole there or else in the second position.

**Comment by AlienKevin** [comment]
@cyrus- Most of it make sense, except I'm not sure what to do when you press a comma at the beginning of a hole, like this:
```
let x : (Int, Int) = |_ in ...
```
After you press the comma, it will turn into:
```
let x : (Int, Int) = _ ,_ in ...
```
I think in this case, it makes more sense to place the cursor at the first hole before the comma.

As for the `5| 6` situation of a 3-tuple. Are you referring to something like this?
```
let x : (Int, Int, Int) = (5|, 6)
```
After pressing comma, Hazel will currently insert a hole after 5:
```
let x : (Int, Int, Int) = (5, |_, 6)
```
So the inserted hole is also at the next position after the comma. Doesn't seem like an edge case to me.

**Comment by AlienKevin** [comment]
Edge cases not solved:
1. let x : (Int, Int) = |_ in
Cursor at left of hole, press "," only inserts one hole before the cursor and places cursor after the comma.
2. let x : (Int, Int, Int) = 3, 4| in
Cursor at right of 4, press "," places cursor after the second ","
