### ISSUE TITLE
cascaded type annotation in let position

### ISSUE THREAD

**Issue by LighghtEeloo** [hazelgrove/hazel#594]
Type `:` at position of the cursor will generate cascaded type annotation

<img width="323" alt="Screen Shot 2022-06-09 at 20 47 23" src="https://user-images.githubusercontent.com/24841828/172968994-5fcc9447-413f-45af-8308-ec815c5a0b40.png">

**Comment by disconcision** [comment]
hmm, i remember we talked about this when implementing annotations... i seem to recall the consensus was just to allow it rather than special-case its prevention, as it is grammatically valid and has reasonable (if redundant) semantics.

if we wanted to get rid of it, i suppose there are two levels of generality. we could forbid only this case: an annotation of an annotation, or we could forbid the more general but ultimately equally redundant case of any annotation nested (however deeply) within another.

thinking a bit more, i guess this gets more interesting with eg type variables e.g. `let (x:'a, y:int):'a = ... in ...`.

**Comment by LighghtEeloo** [comment]
I also agree that cascaded type annotations can be more of a feature of a manual casting than a bug. User may want to use such utility.

Btw, I also found this working:

<img width="859" alt="Screen Shot 2022-06-10 at 15 16 56" src="https://user-images.githubusercontent.com/24841828/173135450-5db092b4-6693-4a6a-8756-50958f08c9e2.png">

which afaik is not intended, even if we allow "type casts". Is that correct?

**Comment by disconcision** [comment]
yep, looks like a bug. synthesis of `<pat> : <typ>`, should always yield typ, so x shouldn't be float. appears to already be fixed by #566 , hopefully to be merged soon, which addresses several issues with pattern annotations (try it here: https://hazel.org/build/make-impossible-syn-more-impossibler/ )

**Comment by cyrus-** [comment]
I think if we're going to prevent cascaded type annotations when to the right of the type, we should also do so around the colon, otherwise it feels like we missed something. There really isn't a good use for this feature, so I'm in favor of disabling directly cascading type annotations. (Not necessary to disable it for when there is a type annotation deeper in the pattern though.)
